# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.19"

# Optional: Optimizer settings (good for production)
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
rsk_testnet = "https://public-node.testnet.rsk.co"

[etherscan]
rsk_testnet = { key = "${RSK_API_KEY}", url = "https://rootstock-testnet.blockscout.com/api" }
